#ifndef __sort_h__
#define __sort_h__

// DO NOT EDIT THIS FILE

#define NUMRECS (24)

typedef struct __rec_t {
    unsigned int key;
    unsigned int record[NUMRECS];
} rec_t;



#endif // __sort_h__

